# -*- coding: utf-8 -*-
#
__version__ = "1.01.00"

# Logging Levels
INSTAMSG_LOG_LEVEL_DISABLED = 0
INSTAMSG_LOG_LEVEL_INFO = 1
INSTAMSG_LOG_LEVEL_ERROR = 2
INSTAMSG_LOG_LEVEL_DEBUG = 3
# Logging Level String
INSTAMSG_LOG_LEVEL = {0:"DISABLED", 1:"INFO", 2:"ERROR", 3:"DEBUG"}
# Error codes
INSTAMSG_ERROR_TIMEOUT = 0
INSTAMSG_ERROR_NO_HANDLERS = 1
INSTAMSG_ERROR_SOCKET = 2
INSTAMSG_ERROR_AUTHENTICATION = 3
# Message QOS
INSTAMSG_QOS0 = 0
INSTAMSG_QOS1 = 1
INSTAMSG_QOS2 = 2
#Provisioning States
PROVISIONIG_STARTED = 0
PROVISIONIG_SMS_READ = 1
PROVISIONIG_MSG_SENT = 2
PROVISIONING_COMPLETED = 3
PROVISIONING_FAILED = 4
#Client Info
NETWORK_INFO_PUBLISH_INTERVAL = 300
INSTAMSG_MAX_BYTES_IN_MSG = 10240
INSTAMSG_KEEP_ALIVE_TIMER = 60
INSTAMSG_RECONNECT_TIMER = 30
INSTAMSG_HOST = "device.instamsg.io"
INSTAMSG_PORT = 1883
INSTAMSG_PORT_SSL = 8883
INSTAMSG_PORT_WS = 80
INSTAMSG_PORT_WS_SSL = 443
INSTAMSG_HTTP_HOST = 'platform.instamsg.io'
INSTAMSG_HTTP_PORT = 80
INSTAMSG_HTTPS_PORT = 443
INSTAMSG_API_VERSION = "1.0"
INSTAMSG_RESULT_HANDLER_TIMEOUT = 10    
INSTAMSG_MSG_REPLY_HANDLER_TIMEOUT = 10
# InstaMsg Versions // Update every time when some changes happened in this file.
INSTAMSG_VERSION = __version__